/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.daffo.Form_di_segnalService.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.daffo.Form_di_segnalService.model.Form_di_segnalazione_service;
import com.daffo.Form_di_segnalService.service.Form_di_segnalazione_serviceLocalServiceUtil;

/**
 * The extended model base implementation for the Form_di_segnalazione_service service. Represents a row in the &quot;form_di_segnalazione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Form_di_segnalazione_serviceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Form_di_segnalazione_serviceImpl
 * @see Form_di_segnalazione_service
 * @generated
 */
@ProviderType
public abstract class Form_di_segnalazione_serviceBaseImpl
	extends Form_di_segnalazione_serviceModelImpl
	implements Form_di_segnalazione_service {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a form_di_segnalazione_service model instance should use the {@link Form_di_segnalazione_service} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			Form_di_segnalazione_serviceLocalServiceUtil.addForm_di_segnalazione_service(this);
		}
		else {
			Form_di_segnalazione_serviceLocalServiceUtil.updateForm_di_segnalazione_service(this);
		}
	}
}