/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.daffo.prontuario_drugservice.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.daffo.prontuario_drugservice.model.prontuario_drug;
import com.daffo.prontuario_drugservice.service.prontuario_drugLocalServiceUtil;

/**
 * The extended model base implementation for the prontuario_drug service. Represents a row in the &quot;prontuario_drug&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link prontuario_drugImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see prontuario_drugImpl
 * @see prontuario_drug
 * @generated
 */
@ProviderType
public abstract class prontuario_drugBaseImpl extends prontuario_drugModelImpl
	implements prontuario_drug {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a prontuario_drug model instance should use the {@link prontuario_drug} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			prontuario_drugLocalServiceUtil.addprontuario_drug(this);
		}
		else {
			prontuario_drugLocalServiceUtil.updateprontuario_drug(this);
		}
	}
}