/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.daffo.wiki_node_tableservice.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.daffo.wiki_node_tableservice.model.wiki_pagedata_table;
import com.daffo.wiki_node_tableservice.model.wiki_pagedata_tableModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the wiki_pagedata_table service. Represents a row in the &quot;wiki_pagedata_table&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link wiki_pagedata_tableModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link wiki_pagedata_tableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see wiki_pagedata_tableImpl
 * @see wiki_pagedata_table
 * @see wiki_pagedata_tableModel
 * @generated
 */
@ProviderType
public class wiki_pagedata_tableModelImpl extends BaseModelImpl<wiki_pagedata_table>
	implements wiki_pagedata_tableModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a wiki_pagedata_table model instance should use the {@link wiki_pagedata_table} interface instead.
	 */
	public static final String TABLE_NAME = "wiki_pagedata_table";
	public static final Object[][] TABLE_COLUMNS = {
			{ "Page_ModID", Types.BIGINT },
			{ "PageData", Types.VARCHAR },
			{ "PageEdit_User", Types.VARCHAR },
			{ "Page_editDate", Types.VARCHAR },
			{ "Page_Version", Types.VARCHAR },
			{ "PageID", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Page_ModID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("PageData", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PageEdit_User", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Page_editDate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Page_Version", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("PageID", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table wiki_pagedata_table (Page_ModID LONG not null primary key,PageData VARCHAR(75) null,PageEdit_User VARCHAR(75) null,Page_editDate VARCHAR(75) null,Page_Version VARCHAR(75) null,PageID LONG)";
	public static final String TABLE_SQL_DROP = "drop table wiki_pagedata_table";
	public static final String ORDER_BY_JPQL = " ORDER BY wiki_pagedata_table.Page_ModID ASC";
	public static final String ORDER_BY_SQL = " ORDER BY wiki_pagedata_table.Page_ModID ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.daffo.wiki_node_tableservice.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.daffo.wiki_node_tableservice.model.wiki_pagedata_table"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.daffo.wiki_node_tableservice.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.daffo.wiki_node_tableservice.model.wiki_pagedata_table"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.daffo.wiki_node_tableservice.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.daffo.wiki_node_tableservice.model.wiki_pagedata_table"),
			true);
	public static final long PAGEID_COLUMN_BITMASK = 1L;
	public static final long PAGE_MODID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.daffo.wiki_node_tableservice.service.util.ServiceProps.get(
				"lock.expiration.time.com.daffo.wiki_node_tableservice.model.wiki_pagedata_table"));

	public wiki_pagedata_tableModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Page_ModID;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPage_ModID(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Page_ModID;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return wiki_pagedata_table.class;
	}

	@Override
	public String getModelClassName() {
		return wiki_pagedata_table.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("Page_ModID", getPage_ModID());
		attributes.put("PageData", getPageData());
		attributes.put("PageEdit_User", getPageEdit_User());
		attributes.put("Page_editDate", getPage_editDate());
		attributes.put("Page_Version", getPage_Version());
		attributes.put("PageID", getPageID());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long Page_ModID = (Long)attributes.get("Page_ModID");

		if (Page_ModID != null) {
			setPage_ModID(Page_ModID);
		}

		String PageData = (String)attributes.get("PageData");

		if (PageData != null) {
			setPageData(PageData);
		}

		String PageEdit_User = (String)attributes.get("PageEdit_User");

		if (PageEdit_User != null) {
			setPageEdit_User(PageEdit_User);
		}

		String Page_editDate = (String)attributes.get("Page_editDate");

		if (Page_editDate != null) {
			setPage_editDate(Page_editDate);
		}

		String Page_Version = (String)attributes.get("Page_Version");

		if (Page_Version != null) {
			setPage_Version(Page_Version);
		}

		Long PageID = (Long)attributes.get("PageID");

		if (PageID != null) {
			setPageID(PageID);
		}
	}

	@Override
	public long getPage_ModID() {
		return _Page_ModID;
	}

	@Override
	public void setPage_ModID(long Page_ModID) {
		_Page_ModID = Page_ModID;
	}

	@Override
	public String getPageData() {
		if (_PageData == null) {
			return StringPool.BLANK;
		}
		else {
			return _PageData;
		}
	}

	@Override
	public void setPageData(String PageData) {
		_PageData = PageData;
	}

	@Override
	public String getPageEdit_User() {
		if (_PageEdit_User == null) {
			return StringPool.BLANK;
		}
		else {
			return _PageEdit_User;
		}
	}

	@Override
	public void setPageEdit_User(String PageEdit_User) {
		_PageEdit_User = PageEdit_User;
	}

	@Override
	public String getPage_editDate() {
		if (_Page_editDate == null) {
			return StringPool.BLANK;
		}
		else {
			return _Page_editDate;
		}
	}

	@Override
	public void setPage_editDate(String Page_editDate) {
		_Page_editDate = Page_editDate;
	}

	@Override
	public String getPage_Version() {
		if (_Page_Version == null) {
			return StringPool.BLANK;
		}
		else {
			return _Page_Version;
		}
	}

	@Override
	public void setPage_Version(String Page_Version) {
		_Page_Version = Page_Version;
	}

	@Override
	public long getPageID() {
		return _PageID;
	}

	@Override
	public void setPageID(long PageID) {
		_columnBitmask |= PAGEID_COLUMN_BITMASK;

		if (!_setOriginalPageID) {
			_setOriginalPageID = true;

			_originalPageID = _PageID;
		}

		_PageID = PageID;
	}

	public long getOriginalPageID() {
		return _originalPageID;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			wiki_pagedata_table.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public wiki_pagedata_table toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (wiki_pagedata_table)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		wiki_pagedata_tableImpl wiki_pagedata_tableImpl = new wiki_pagedata_tableImpl();

		wiki_pagedata_tableImpl.setPage_ModID(getPage_ModID());
		wiki_pagedata_tableImpl.setPageData(getPageData());
		wiki_pagedata_tableImpl.setPageEdit_User(getPageEdit_User());
		wiki_pagedata_tableImpl.setPage_editDate(getPage_editDate());
		wiki_pagedata_tableImpl.setPage_Version(getPage_Version());
		wiki_pagedata_tableImpl.setPageID(getPageID());

		wiki_pagedata_tableImpl.resetOriginalValues();

		return wiki_pagedata_tableImpl;
	}

	@Override
	public int compareTo(wiki_pagedata_table wiki_pagedata_table) {
		long primaryKey = wiki_pagedata_table.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof wiki_pagedata_table)) {
			return false;
		}

		wiki_pagedata_table wiki_pagedata_table = (wiki_pagedata_table)obj;

		long primaryKey = wiki_pagedata_table.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		wiki_pagedata_tableModelImpl wiki_pagedata_tableModelImpl = this;

		wiki_pagedata_tableModelImpl._originalPageID = wiki_pagedata_tableModelImpl._PageID;

		wiki_pagedata_tableModelImpl._setOriginalPageID = false;

		wiki_pagedata_tableModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<wiki_pagedata_table> toCacheModel() {
		wiki_pagedata_tableCacheModel wiki_pagedata_tableCacheModel = new wiki_pagedata_tableCacheModel();

		wiki_pagedata_tableCacheModel.Page_ModID = getPage_ModID();

		wiki_pagedata_tableCacheModel.PageData = getPageData();

		String PageData = wiki_pagedata_tableCacheModel.PageData;

		if ((PageData != null) && (PageData.length() == 0)) {
			wiki_pagedata_tableCacheModel.PageData = null;
		}

		wiki_pagedata_tableCacheModel.PageEdit_User = getPageEdit_User();

		String PageEdit_User = wiki_pagedata_tableCacheModel.PageEdit_User;

		if ((PageEdit_User != null) && (PageEdit_User.length() == 0)) {
			wiki_pagedata_tableCacheModel.PageEdit_User = null;
		}

		wiki_pagedata_tableCacheModel.Page_editDate = getPage_editDate();

		String Page_editDate = wiki_pagedata_tableCacheModel.Page_editDate;

		if ((Page_editDate != null) && (Page_editDate.length() == 0)) {
			wiki_pagedata_tableCacheModel.Page_editDate = null;
		}

		wiki_pagedata_tableCacheModel.Page_Version = getPage_Version();

		String Page_Version = wiki_pagedata_tableCacheModel.Page_Version;

		if ((Page_Version != null) && (Page_Version.length() == 0)) {
			wiki_pagedata_tableCacheModel.Page_Version = null;
		}

		wiki_pagedata_tableCacheModel.PageID = getPageID();

		return wiki_pagedata_tableCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{Page_ModID=");
		sb.append(getPage_ModID());
		sb.append(", PageData=");
		sb.append(getPageData());
		sb.append(", PageEdit_User=");
		sb.append(getPageEdit_User());
		sb.append(", Page_editDate=");
		sb.append(getPage_editDate());
		sb.append(", Page_Version=");
		sb.append(getPage_Version());
		sb.append(", PageID=");
		sb.append(getPageID());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.daffo.wiki_node_tableservice.model.wiki_pagedata_table");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>Page_ModID</column-name><column-value><![CDATA[");
		sb.append(getPage_ModID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PageData</column-name><column-value><![CDATA[");
		sb.append(getPageData());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PageEdit_User</column-name><column-value><![CDATA[");
		sb.append(getPageEdit_User());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Page_editDate</column-name><column-value><![CDATA[");
		sb.append(getPage_editDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Page_Version</column-name><column-value><![CDATA[");
		sb.append(getPage_Version());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>PageID</column-name><column-value><![CDATA[");
		sb.append(getPageID());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = wiki_pagedata_table.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			wiki_pagedata_table.class
		};
	private long _Page_ModID;
	private String _PageData;
	private String _PageEdit_User;
	private String _Page_editDate;
	private String _Page_Version;
	private long _PageID;
	private long _originalPageID;
	private boolean _setOriginalPageID;
	private long _columnBitmask;
	private wiki_pagedata_table _escapedModel;
}