/*
SQLyog Ultimate v8.55 
MySQL - 5.7.12-log : Database - liferaynew_1
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `form_di_segnalazione` */

DROP TABLE IF EXISTS `form_di_segnalazione`;

CREATE TABLE `form_di_segnalazione` (
  `Form_di_segnalazione_id` mediumint(20) NOT NULL,
  `CODICE` varchar(500) DEFAULT NULL,
  `INIZIALI_1` varchar(500) DEFAULT NULL,
  `INIZIALI_1_a` varchar(500) DEFAULT NULL,
  `INIZIALI_1_b` varchar(500) DEFAULT NULL,
  `INIZIALI_1_c` varchar(500) DEFAULT NULL,
  `INIZIALI_1_d` varchar(500) DEFAULT NULL,
  `INIZIALI_1_e` varchar(500) DEFAULT NULL,
  `DATA_2` varchar(500) DEFAULT NULL,
  `SESSO_3` varchar(500) DEFAULT NULL,
  `DATA_4` varchar(500) DEFAULT NULL,
  `ORIGINE_5` varchar(500) DEFAULT NULL,
  `DESCRIZIONE_6` text,
  `INDICARE_7_1` varchar(500) DEFAULT NULL,
  `INDICARE_7_2` varchar(500) DEFAULT NULL,
  `INDICARE_7_3` varchar(500) DEFAULT NULL,
  `INDICARE_7_4` varchar(500) DEFAULT NULL,
  `INDICARE_7_5` varchar(500) DEFAULT NULL,
  `INDICARE_7_6` varchar(500) DEFAULT NULL,
  `INDICARE_7_7` varchar(500) DEFAULT NULL,
  `GRAVITA_8_1` varchar(500) DEFAULT NULL,
  `GRAVITA_8_2` varchar(500) DEFAULT NULL,
  `GRAVITA_8_3` varchar(500) DEFAULT NULL,
  `GRAVITA_8_4` varchar(500) DEFAULT NULL,
  `GRAVITA_8_5` varchar(500) DEFAULT NULL,
  `GRAVITA_8_6` varchar(500) DEFAULT NULL,
  `GRAVITA_8_7` varchar(500) DEFAULT NULL,
  `EVENTUALI_9` text,
  `ESITO_10` text,
  `ESITO_10_1` varchar(500) DEFAULT NULL,
  `ESITO_10_2` varchar(500) DEFAULT NULL,
  `ESITO_10_3` varchar(500) DEFAULT NULL,
  `ESITO_10_4` varchar(500) DEFAULT NULL,
  `ESITO_10_5` varchar(500) DEFAULT NULL,
  `ESITO_10_6` varchar(500) DEFAULT NULL,
  `ESITO_10_7` varchar(500) DEFAULT NULL,
  `ESITO_10_8` varchar(500) DEFAULT NULL,
  `ESITO_10_9` varchar(500) DEFAULT NULL,
  `ESITO_10_10` varchar(500) DEFAULT NULL,
  `AZIONI_11` varchar(500) DEFAULT NULL,
  `FARMACO_12_a` varchar(500) DEFAULT NULL,
  `FARMACO_12_a_13` varchar(500) DEFAULT NULL,
  `FARMACO_12_a_14` varchar(500) DEFAULT NULL,
  `FARMACO_12_a_15` varchar(500) DEFAULT NULL,
  `FARMACO_12_a_16_1` varchar(500) DEFAULT NULL,
  `FARMACO_12_a_16_2` varchar(500) DEFAULT NULL,
  `FARMACO_12_a_17` varchar(500) DEFAULT NULL,
  `FARMACO_12_a_18` varchar(500) DEFAULT NULL,
  `FARMACO_12_a_19` varchar(500) DEFAULT NULL,
  `FARMACO_12_a_20` varchar(500) DEFAULT NULL,
  `FARMACO_12_b` varchar(500) DEFAULT NULL,
  `FARMACO_12_b_13` varchar(500) DEFAULT NULL,
  `FARMACO_12_b_14` varchar(500) DEFAULT NULL,
  `FARMACO_12_b_15` varchar(500) DEFAULT NULL,
  `FARMACO_12_b_16_1` varchar(500) DEFAULT NULL,
  `FARMACO_12_b_16_2` varchar(500) DEFAULT NULL,
  `FARMACO_12_b_17` varchar(500) DEFAULT NULL,
  `FARMACO_12_b_18` varchar(500) DEFAULT NULL,
  `FARMACO_12_b_19` varchar(500) DEFAULT NULL,
  `FARMACO_12_b_20` varchar(500) DEFAULT NULL,
  `FARMACO_12_c` varchar(500) DEFAULT NULL,
  `FARMACO_12_c_13` varchar(500) DEFAULT NULL,
  `FARMACO_12_c_14` varchar(500) DEFAULT NULL,
  `FARMACO_12_c_15` varchar(500) DEFAULT NULL,
  `FARMACO_12_c_16_1` varchar(500) DEFAULT NULL,
  `FARMACO_12_c_16_2` varchar(500) DEFAULT NULL,
  `FARMACO_12_c_17` varchar(500) DEFAULT NULL,
  `FARMACO_12_c_18` varchar(500) DEFAULT NULL,
  `FARMACO_12_c_19` varchar(500) DEFAULT NULL,
  `FARMACO_12_c_20` varchar(500) DEFAULT NULL,
  `INDICAZIONI_21_a` varchar(500) DEFAULT NULL,
  `INDICAZIONI_21_b` varchar(500) DEFAULT NULL,
  `INDICAZIONI_21_c` varchar(500) DEFAULT NULL,
  `FARMACO_22_a` varchar(500) DEFAULT NULL,
  `FARMACO_22_a_23` varchar(500) DEFAULT NULL,
  `FARMACO_22_a_24` varchar(500) DEFAULT NULL,
  `FARMACO_22_a_25` varchar(500) DEFAULT NULL,
  `FARMACO_22_a_26_1` varchar(500) DEFAULT NULL,
  `FARMACO_22_a_26_2` varchar(500) DEFAULT NULL,
  `FARMACO_22_a_27` varchar(500) DEFAULT NULL,
  `FARMACO_22_a_28` varchar(500) DEFAULT NULL,
  `FARMACO_22_a_29` varchar(500) DEFAULT NULL,
  `FARMACO_22_a_30` varchar(500) DEFAULT NULL,
  `FARMACO_22_b` varchar(500) DEFAULT NULL,
  `FARMACO_22_b_23` varchar(500) DEFAULT NULL,
  `FARMACO_22_b_24` varchar(500) DEFAULT NULL,
  `FARMACO_22_b_25` varchar(500) DEFAULT NULL,
  `FARMACO_22_b_26_1` varchar(500) DEFAULT NULL,
  `FARMACO_22_b_26_2` varchar(500) DEFAULT NULL,
  `FARMACO_22_b_27` varchar(500) DEFAULT NULL,
  `FARMACO_22_b_28` varchar(500) DEFAULT NULL,
  `FARMACO_22_b_29` varchar(500) DEFAULT NULL,
  `FARMACO_22_b_30` varchar(500) DEFAULT NULL,
  `INDICAZIONI_31_a` varchar(500) DEFAULT NULL,
  `INDICAZIONI_31_b` varchar(500) DEFAULT NULL,
  `USO_32` text,
  `CONDIZIONI_33` text,
  `ALTRE_34` text,
  `INDICARE_35_1` varchar(500) DEFAULT NULL,
  `INDICARE_35_2` varchar(500) DEFAULT NULL,
  `INDICARE_35_3` varchar(500) DEFAULT NULL,
  `INDICARE_35_4` varchar(500) DEFAULT NULL,
  `INDICARE_35_5` varchar(500) DEFAULT NULL,
  `INDICARE_35_6` varchar(500) DEFAULT NULL,
  `QUALIFICA_36_1` varchar(500) DEFAULT NULL,
  `QUALIFICA_36_2` varchar(500) DEFAULT NULL,
  `QUALIFICA_36_3` varchar(500) DEFAULT NULL,
  `QUALIFICA_36_4` varchar(500) DEFAULT NULL,
  `QUALIFICA_36_5` varchar(500) DEFAULT NULL,
  `QUALIFICA_36_6` varchar(500) DEFAULT NULL,
  `QUALIFICA_36_7` varchar(500) DEFAULT NULL,
  `QUALIFICA_36_8` varchar(500) DEFAULT NULL,
  `QUALIFICA_36_9` varchar(500) DEFAULT NULL,
  `QUALIFICA_36_10` varchar(500) DEFAULT NULL,
  `DATI_37_1` varchar(500) DEFAULT NULL,
  `DATI_37_2` varchar(500) DEFAULT NULL,
  `DATI_37_3` varchar(500) DEFAULT NULL,
  `DATI_37_4` varchar(500) DEFAULT NULL,
  `ASL_38` varchar(500) DEFAULT NULL,
  `REGIONE_39` varchar(500) DEFAULT NULL,
  `DATA_40` varchar(500) DEFAULT NULL,
  `FIRMA_41` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`Form_di_segnalazione_id`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

/*Data for the table `form_di_segnalazione` */

insert  into `form_di_segnalazione`(`Form_di_segnalazione_id`,`CODICE`,`INIZIALI_1`,`INIZIALI_1_a`,`INIZIALI_1_b`,`INIZIALI_1_c`,`INIZIALI_1_d`,`INIZIALI_1_e`,`DATA_2`,`SESSO_3`,`DATA_4`,`ORIGINE_5`,`DESCRIZIONE_6`,`INDICARE_7_1`,`INDICARE_7_2`,`INDICARE_7_3`,`INDICARE_7_4`,`INDICARE_7_5`,`INDICARE_7_6`,`INDICARE_7_7`,`GRAVITA_8_1`,`GRAVITA_8_2`,`GRAVITA_8_3`,`GRAVITA_8_4`,`GRAVITA_8_5`,`GRAVITA_8_6`,`GRAVITA_8_7`,`EVENTUALI_9`,`ESITO_10`,`ESITO_10_1`,`ESITO_10_2`,`ESITO_10_3`,`ESITO_10_4`,`ESITO_10_5`,`ESITO_10_6`,`ESITO_10_7`,`ESITO_10_8`,`ESITO_10_9`,`ESITO_10_10`,`AZIONI_11`,`FARMACO_12_a`,`FARMACO_12_a_13`,`FARMACO_12_a_14`,`FARMACO_12_a_15`,`FARMACO_12_a_16_1`,`FARMACO_12_a_16_2`,`FARMACO_12_a_17`,`FARMACO_12_a_18`,`FARMACO_12_a_19`,`FARMACO_12_a_20`,`FARMACO_12_b`,`FARMACO_12_b_13`,`FARMACO_12_b_14`,`FARMACO_12_b_15`,`FARMACO_12_b_16_1`,`FARMACO_12_b_16_2`,`FARMACO_12_b_17`,`FARMACO_12_b_18`,`FARMACO_12_b_19`,`FARMACO_12_b_20`,`FARMACO_12_c`,`FARMACO_12_c_13`,`FARMACO_12_c_14`,`FARMACO_12_c_15`,`FARMACO_12_c_16_1`,`FARMACO_12_c_16_2`,`FARMACO_12_c_17`,`FARMACO_12_c_18`,`FARMACO_12_c_19`,`FARMACO_12_c_20`,`INDICAZIONI_21_a`,`INDICAZIONI_21_b`,`INDICAZIONI_21_c`,`FARMACO_22_a`,`FARMACO_22_a_23`,`FARMACO_22_a_24`,`FARMACO_22_a_25`,`FARMACO_22_a_26_1`,`FARMACO_22_a_26_2`,`FARMACO_22_a_27`,`FARMACO_22_a_28`,`FARMACO_22_a_29`,`FARMACO_22_a_30`,`FARMACO_22_b`,`FARMACO_22_b_23`,`FARMACO_22_b_24`,`FARMACO_22_b_25`,`FARMACO_22_b_26_1`,`FARMACO_22_b_26_2`,`FARMACO_22_b_27`,`FARMACO_22_b_28`,`FARMACO_22_b_29`,`FARMACO_22_b_30`,`INDICAZIONI_31_a`,`INDICAZIONI_31_b`,`USO_32`,`CONDIZIONI_33`,`ALTRE_34`,`INDICARE_35_1`,`INDICARE_35_2`,`INDICARE_35_3`,`INDICARE_35_4`,`INDICARE_35_5`,`INDICARE_35_6`,`QUALIFICA_36_1`,`QUALIFICA_36_2`,`QUALIFICA_36_3`,`QUALIFICA_36_4`,`QUALIFICA_36_5`,`QUALIFICA_36_6`,`QUALIFICA_36_7`,`QUALIFICA_36_8`,`QUALIFICA_36_9`,`QUALIFICA_36_10`,`DATI_37_1`,`DATI_37_2`,`DATI_37_3`,`DATI_37_4`,`ASL_38`,`REGIONE_39`,`DATA_40`,`FIRMA_41`) values (39072,'COD-102','sdasd',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'sadas','sadasd','asdasdasdasas\ndas\nd\nas','asdas\ndas\nd\nasd\nas','sadas\ndasdas','Progetto di Farmacovigilanza Attiva','Registro Farmaci','Studio Osservazionale','asd','asdas','asd','MEDICO OSPEDALIERO','MEDICO MEDICINA GENERALE','PEDIATRA LIBERA SCELTA','SPECIALISTA','MEDICO DISTRETTO','RARMACISTA','INFERMIERE',NULL,NULL,'asdasd','sad','asd','asd','sada@gmail.com','asd','asd','28/06/2017','sada'),(39073,'sdfsd','fsdfsd','44','234','234','sconosciuta','SI','21/06/2017','F','20/06/2017','sdfsd','23432','INTERAZIONE',NULL,NULL,NULL,NULL,'OVERDOSE',NULL,'DECESSO',NULL,NULL,NULL,NULL,'ALTRA CONDIZIONE CLINICAMENTE RILEVANTE','NON GRAVE','sdfsd','sdfsd','RISOLUZIONE COMPLETA ADR',NULL,NULL,NULL,'DECESSO',NULL,NULL,'non dovuto al farmaco',NULL,'NON DISPONIBILE','sdfs','sdf','sdf','sdf','sdf','sdf','sdf','SI','SI','NO','SI','erfwe','erew','wer','wer','wer','wer','SI','SI','NO','SI','wer','wer','wer','wer','wer','we','SI','SI','NO','SI','wer','wer','erw','we','we','we','ewr','wer','wer','SI','SI','NO','NO','wer','wer','wer','wer','wer','wer','NO','NO','NO','NO','wer','wer','er\nwer\nwe\nwer','ewrwe\nwer\nwer\nwer','wer\nwer\nwer','Progetto di Farmacovigilanza Attiva',NULL,'Studio Osservazionale',NULL,'ewr','wer','MEDICO OSPEDALIERO',NULL,NULL,'SPECIALISTA','MEDICO DISTRETTO',NULL,'INFERMIERE',NULL,NULL,NULL,'ewr','ewr','wer','sdf@gmail.com','asd','sda','06/06/2017','asd'),(38599,'asdas','sdas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'a','sdfas','sada','asd','asda','asd','SI','NO','NO','SI','asd','asda','sada','asd','asd','asda','SI','SI','NO','SI','sd','asd','asd','asd','asd','asd','SI','SI','SI','SI','dfas','sda','sad','asd','sad','asd','asd','asd','asd','SI','SI','NO','SI','asd','asd','sad','as','asd','sad','SI','SI','NO','SI',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(38598,'asdas','asdsad','sad','asd','asd','3Â° trimestre','NO','21/06/2017','F','28/06/2017','sadas','sad','INTERAZIONE',NULL,'ABUSO',NULL,'OFF LABEL','OVERDOSE',NULL,'DECESSO',NULL,'INVALIDITA\' GRAVE O PERMANENTE','HA MESSO IN PERICOLO DI VITA',NULL,'ALTRA CONDIZIONE CLINICAMENTE RILEVANTE',NULL,'sadasd','asdas',NULL,'RISOLUZIONE CON POSTUMI',NULL,'REAZIONE INVARIATA O PEGGIORATA',NULL,'dovuto alla reazione avversa',NULL,'non dovuto al farmaco',NULL,NULL,'sada',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(38597,'sada','sda',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(38596,'sdad','sadas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),(38595,'sdsada','asdasd','11','11','11','2Â° trimestre','SI','06/06/2017','M','27/06/2017','sadsa','asdasd\nsd\nas\nRajat','INTERAZIONE',NULL,NULL,NULL,NULL,'OVERDOSE',NULL,NULL,NULL,NULL,NULL,NULL,'ALTRA CONDIZIONE CLINICAMENTE RILEVANTE',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'08/06/2017','asdas'),(39675,'COD-709','dfgdfg',NULL,NULL,NULL,'2Â° trimestre','SI','13/06/2017','M','21/06/2017','fgdf',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'INVALIDITA\' GRAVE O PERMANENTE',NULL,NULL,NULL,'NON GRAVE','fgd',NULL,NULL,NULL,NULL,NULL,'DECESSO',NULL,NULL,NULL,NULL,'NON DISPONIBILE','fdgdf',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'SI',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'SI',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'SI','SI',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*Table structure for table `prontuario_drug` */

DROP TABLE IF EXISTS `prontuario_drug`;

CREATE TABLE `prontuario_drug` (
  `drug_id` bigint(20) NOT NULL,
  `Gruppo` varchar(500) DEFAULT NULL,
  `SottoGruppo` varchar(500) DEFAULT NULL,
  `Codice` varchar(500) DEFAULT NULL,
  `Principio_Attivo` varchar(500) DEFAULT NULL,
  `Nome_Commerciale` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`drug_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `prontuario_drug` */

insert  into `prontuario_drug`(`drug_id`,`Gruppo`,`SottoGruppo`,`Codice`,`Principio_Attivo`,`Nome_Commerciale`) values (1,'ss','ss','ss','ss','ss');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
