/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.daffo.form_di_segnalazione.service.base;

import aQute.bnd.annotation.ProviderType;

import com.daffo.form_di_segnalazione.model.form_di_segnalazione;
import com.daffo.form_di_segnalazione.service.form_di_segnalazioneLocalService;
import com.daffo.form_di_segnalazione.service.persistence.form_di_segnalazionePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the form_di_segnalazione local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.daffo.form_di_segnalazione.service.impl.form_di_segnalazioneLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.daffo.form_di_segnalazione.service.impl.form_di_segnalazioneLocalServiceImpl
 * @see com.daffo.form_di_segnalazione.service.form_di_segnalazioneLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class form_di_segnalazioneLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements form_di_segnalazioneLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.daffo.form_di_segnalazione.service.form_di_segnalazioneLocalServiceUtil} to access the form_di_segnalazione local service.
	 */

	/**
	 * Adds the form_di_segnalazione to the database. Also notifies the appropriate model listeners.
	 *
	 * @param form_di_segnalazione the form_di_segnalazione
	 * @return the form_di_segnalazione that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public form_di_segnalazione addform_di_segnalazione(
		form_di_segnalazione form_di_segnalazione) {
		form_di_segnalazione.setNew(true);

		return form_di_segnalazionePersistence.update(form_di_segnalazione);
	}

	/**
	 * Creates a new form_di_segnalazione with the primary key. Does not add the form_di_segnalazione to the database.
	 *
	 * @param Form_di_segnalazione_id the primary key for the new form_di_segnalazione
	 * @return the new form_di_segnalazione
	 */
	@Override
	public form_di_segnalazione createform_di_segnalazione(
		long Form_di_segnalazione_id) {
		return form_di_segnalazionePersistence.create(Form_di_segnalazione_id);
	}

	/**
	 * Deletes the form_di_segnalazione with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param Form_di_segnalazione_id the primary key of the form_di_segnalazione
	 * @return the form_di_segnalazione that was removed
	 * @throws PortalException if a form_di_segnalazione with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public form_di_segnalazione deleteform_di_segnalazione(
		long Form_di_segnalazione_id) throws PortalException {
		return form_di_segnalazionePersistence.remove(Form_di_segnalazione_id);
	}

	/**
	 * Deletes the form_di_segnalazione from the database. Also notifies the appropriate model listeners.
	 *
	 * @param form_di_segnalazione the form_di_segnalazione
	 * @return the form_di_segnalazione that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public form_di_segnalazione deleteform_di_segnalazione(
		form_di_segnalazione form_di_segnalazione) {
		return form_di_segnalazionePersistence.remove(form_di_segnalazione);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(form_di_segnalazione.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return form_di_segnalazionePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.daffo.form_di_segnalazione.model.impl.form_di_segnalazioneModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return form_di_segnalazionePersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.daffo.form_di_segnalazione.model.impl.form_di_segnalazioneModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return form_di_segnalazionePersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return form_di_segnalazionePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return form_di_segnalazionePersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public form_di_segnalazione fetchform_di_segnalazione(
		long Form_di_segnalazione_id) {
		return form_di_segnalazionePersistence.fetchByPrimaryKey(Form_di_segnalazione_id);
	}

	/**
	 * Returns the form_di_segnalazione with the primary key.
	 *
	 * @param Form_di_segnalazione_id the primary key of the form_di_segnalazione
	 * @return the form_di_segnalazione
	 * @throws PortalException if a form_di_segnalazione with the primary key could not be found
	 */
	@Override
	public form_di_segnalazione getform_di_segnalazione(
		long Form_di_segnalazione_id) throws PortalException {
		return form_di_segnalazionePersistence.findByPrimaryKey(Form_di_segnalazione_id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(form_di_segnalazioneLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(form_di_segnalazione.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"Form_di_segnalazione_id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(form_di_segnalazioneLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(form_di_segnalazione.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"Form_di_segnalazione_id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(form_di_segnalazioneLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(form_di_segnalazione.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"Form_di_segnalazione_id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return form_di_segnalazioneLocalService.deleteform_di_segnalazione((form_di_segnalazione)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return form_di_segnalazionePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the form_di_segnalaziones.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.daffo.form_di_segnalazione.model.impl.form_di_segnalazioneModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of form_di_segnalaziones
	 * @param end the upper bound of the range of form_di_segnalaziones (not inclusive)
	 * @return the range of form_di_segnalaziones
	 */
	@Override
	public List<form_di_segnalazione> getform_di_segnalaziones(int start,
		int end) {
		return form_di_segnalazionePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of form_di_segnalaziones.
	 *
	 * @return the number of form_di_segnalaziones
	 */
	@Override
	public int getform_di_segnalazionesCount() {
		return form_di_segnalazionePersistence.countAll();
	}

	/**
	 * Updates the form_di_segnalazione in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param form_di_segnalazione the form_di_segnalazione
	 * @return the form_di_segnalazione that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public form_di_segnalazione updateform_di_segnalazione(
		form_di_segnalazione form_di_segnalazione) {
		return form_di_segnalazionePersistence.update(form_di_segnalazione);
	}

	/**
	 * Returns the form_di_segnalazione local service.
	 *
	 * @return the form_di_segnalazione local service
	 */
	public form_di_segnalazioneLocalService getform_di_segnalazioneLocalService() {
		return form_di_segnalazioneLocalService;
	}

	/**
	 * Sets the form_di_segnalazione local service.
	 *
	 * @param form_di_segnalazioneLocalService the form_di_segnalazione local service
	 */
	public void setform_di_segnalazioneLocalService(
		form_di_segnalazioneLocalService form_di_segnalazioneLocalService) {
		this.form_di_segnalazioneLocalService = form_di_segnalazioneLocalService;
	}

	/**
	 * Returns the form_di_segnalazione persistence.
	 *
	 * @return the form_di_segnalazione persistence
	 */
	public form_di_segnalazionePersistence getform_di_segnalazionePersistence() {
		return form_di_segnalazionePersistence;
	}

	/**
	 * Sets the form_di_segnalazione persistence.
	 *
	 * @param form_di_segnalazionePersistence the form_di_segnalazione persistence
	 */
	public void setform_di_segnalazionePersistence(
		form_di_segnalazionePersistence form_di_segnalazionePersistence) {
		this.form_di_segnalazionePersistence = form_di_segnalazionePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.daffo.form_di_segnalazione.model.form_di_segnalazione",
			form_di_segnalazioneLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.daffo.form_di_segnalazione.model.form_di_segnalazione");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return form_di_segnalazioneLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return form_di_segnalazione.class;
	}

	protected String getModelClassName() {
		return form_di_segnalazione.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = form_di_segnalazionePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = form_di_segnalazioneLocalService.class)
	protected form_di_segnalazioneLocalService form_di_segnalazioneLocalService;
	@BeanReference(type = form_di_segnalazionePersistence.class)
	protected form_di_segnalazionePersistence form_di_segnalazionePersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}