/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.daffo.suilupposervice.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the suiluppo_equip_allocation service. Represents a row in the &quot;suiluppo_equip_allocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.daffo.suilupposervice.model.impl.suiluppo_equip_allocationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.daffo.suilupposervice.model.impl.suiluppo_equip_allocationImpl}.
 * </p>
 *
 * @author Naveen
 * @see suiluppo_equip_allocation
 * @see com.daffo.suilupposervice.model.impl.suiluppo_equip_allocationImpl
 * @see com.daffo.suilupposervice.model.impl.suiluppo_equip_allocationModelImpl
 * @generated
 */
@ProviderType
public interface suiluppo_equip_allocationModel extends BaseModel<suiluppo_equip_allocation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a suiluppo_equip_allocation model instance should use the {@link suiluppo_equip_allocation} interface instead.
	 */

	/**
	 * Returns the primary key of this suiluppo_equip_allocation.
	 *
	 * @return the primary key of this suiluppo_equip_allocation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this suiluppo_equip_allocation.
	 *
	 * @param primaryKey the primary key of this suiluppo_equip_allocation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the equip_allocat_id of this suiluppo_equip_allocation.
	 *
	 * @return the equip_allocat_id of this suiluppo_equip_allocation
	 */
	public long getEquip_allocat_id();

	/**
	 * Sets the equip_allocat_id of this suiluppo_equip_allocation.
	 *
	 * @param equip_allocat_id the equip_allocat_id of this suiluppo_equip_allocation
	 */
	public void setEquip_allocat_id(long equip_allocat_id);

	/**
	 * Returns the course_id of this suiluppo_equip_allocation.
	 *
	 * @return the course_id of this suiluppo_equip_allocation
	 */
	public long getCourse_id();

	/**
	 * Sets the course_id of this suiluppo_equip_allocation.
	 *
	 * @param course_id the course_id of this suiluppo_equip_allocation
	 */
	public void setCourse_id(long course_id);

	/**
	 * Returns the equip_id of this suiluppo_equip_allocation.
	 *
	 * @return the equip_id of this suiluppo_equip_allocation
	 */
	public long getEquip_id();

	/**
	 * Sets the equip_id of this suiluppo_equip_allocation.
	 *
	 * @param equip_id the equip_id of this suiluppo_equip_allocation
	 */
	public void setEquip_id(long equip_id);

	/**
	 * Returns the equip_allocat_quantity of this suiluppo_equip_allocation.
	 *
	 * @return the equip_allocat_quantity of this suiluppo_equip_allocation
	 */
	public long getEquip_allocat_quantity();

	/**
	 * Sets the equip_allocat_quantity of this suiluppo_equip_allocation.
	 *
	 * @param equip_allocat_quantity the equip_allocat_quantity of this suiluppo_equip_allocation
	 */
	public void setEquip_allocat_quantity(long equip_allocat_quantity);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.daffo.suilupposervice.model.suiluppo_equip_allocation suiluppo_equip_allocation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.daffo.suilupposervice.model.suiluppo_equip_allocation> toCacheModel();

	@Override
	public com.daffo.suilupposervice.model.suiluppo_equip_allocation toEscapedModel();

	@Override
	public com.daffo.suilupposervice.model.suiluppo_equip_allocation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}