/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.daffo.suilupposervice.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the suiluppo_room service. Represents a row in the &quot;suiluppo_room&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.daffo.suilupposervice.model.impl.suiluppo_roomModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.daffo.suilupposervice.model.impl.suiluppo_roomImpl}.
 * </p>
 *
 * @author Naveen
 * @see suiluppo_room
 * @see com.daffo.suilupposervice.model.impl.suiluppo_roomImpl
 * @see com.daffo.suilupposervice.model.impl.suiluppo_roomModelImpl
 * @generated
 */
@ProviderType
public interface suiluppo_roomModel extends BaseModel<suiluppo_room> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a suiluppo_room model instance should use the {@link suiluppo_room} interface instead.
	 */

	/**
	 * Returns the primary key of this suiluppo_room.
	 *
	 * @return the primary key of this suiluppo_room
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this suiluppo_room.
	 *
	 * @param primaryKey the primary key of this suiluppo_room
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the room ID of this suiluppo_room.
	 *
	 * @return the room ID of this suiluppo_room
	 */
	public long getRoomID();

	/**
	 * Sets the room ID of this suiluppo_room.
	 *
	 * @param roomID the room ID of this suiluppo_room
	 */
	public void setRoomID(long roomID);

	/**
	 * Returns the room_name of this suiluppo_room.
	 *
	 * @return the room_name of this suiluppo_room
	 */
	@AutoEscape
	public String getRoom_name();

	/**
	 * Sets the room_name of this suiluppo_room.
	 *
	 * @param room_name the room_name of this suiluppo_room
	 */
	public void setRoom_name(String room_name);

	/**
	 * Returns the room_description of this suiluppo_room.
	 *
	 * @return the room_description of this suiluppo_room
	 */
	@AutoEscape
	public String getRoom_description();

	/**
	 * Sets the room_description of this suiluppo_room.
	 *
	 * @param room_description the room_description of this suiluppo_room
	 */
	public void setRoom_description(String room_description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.daffo.suilupposervice.model.suiluppo_room suiluppo_room);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.daffo.suilupposervice.model.suiluppo_room> toCacheModel();

	@Override
	public com.daffo.suilupposervice.model.suiluppo_room toEscapedModel();

	@Override
	public com.daffo.suilupposervice.model.suiluppo_room toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}