/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.daffo.suilupposervice.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.daffo.suilupposervice.model.suiluppo_equip_allocation;
import com.daffo.suilupposervice.service.suiluppo_equip_allocationLocalServiceUtil;

/**
 * The extended model base implementation for the suiluppo_equip_allocation service. Represents a row in the &quot;suiluppo_equip_allocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link suiluppo_equip_allocationImpl}.
 * </p>
 *
 * @author Naveen
 * @see suiluppo_equip_allocationImpl
 * @see suiluppo_equip_allocation
 * @generated
 */
@ProviderType
public abstract class suiluppo_equip_allocationBaseImpl
	extends suiluppo_equip_allocationModelImpl
	implements suiluppo_equip_allocation {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a suiluppo_equip_allocation model instance should use the {@link suiluppo_equip_allocation} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			suiluppo_equip_allocationLocalServiceUtil.addsuiluppo_equip_allocation(this);
		}
		else {
			suiluppo_equip_allocationLocalServiceUtil.updatesuiluppo_equip_allocation(this);
		}
	}
}