/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.daffo.suilupposervice.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.daffo.suilupposervice.model.suiluppo_equipment;
import com.daffo.suilupposervice.service.suiluppo_equipmentLocalServiceUtil;

/**
 * The extended model base implementation for the suiluppo_equipment service. Represents a row in the &quot;suiluppo_equipment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link suiluppo_equipmentImpl}.
 * </p>
 *
 * @author Naveen
 * @see suiluppo_equipmentImpl
 * @see suiluppo_equipment
 * @generated
 */
@ProviderType
public abstract class suiluppo_equipmentBaseImpl
	extends suiluppo_equipmentModelImpl implements suiluppo_equipment {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a suiluppo_equipment model instance should use the {@link suiluppo_equipment} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			suiluppo_equipmentLocalServiceUtil.addsuiluppo_equipment(this);
		}
		else {
			suiluppo_equipmentLocalServiceUtil.updatesuiluppo_equipment(this);
		}
	}
}