/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.daffo.suilupposervice.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.daffo.suilupposervice.model.suiluppo_equip_allocation;
import com.daffo.suilupposervice.model.suiluppo_equip_allocationModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the suiluppo_equip_allocation service. Represents a row in the &quot;suiluppo_equip_allocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link suiluppo_equip_allocationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link suiluppo_equip_allocationImpl}.
 * </p>
 *
 * @author Naveen
 * @see suiluppo_equip_allocationImpl
 * @see suiluppo_equip_allocation
 * @see suiluppo_equip_allocationModel
 * @generated
 */
@ProviderType
public class suiluppo_equip_allocationModelImpl extends BaseModelImpl<suiluppo_equip_allocation>
	implements suiluppo_equip_allocationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a suiluppo_equip_allocation model instance should use the {@link suiluppo_equip_allocation} interface instead.
	 */
	public static final String TABLE_NAME = "suiluppo_equip_allocation";
	public static final Object[][] TABLE_COLUMNS = {
			{ "equip_allocat_id", Types.BIGINT },
			{ "course_id", Types.BIGINT },
			{ "equip_id", Types.BIGINT },
			{ "equip_allocat_quantity", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("equip_allocat_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("course_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("equip_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("equip_allocat_quantity", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table suiluppo_equip_allocation (equip_allocat_id LONG not null primary key,course_id LONG,equip_id LONG,equip_allocat_quantity LONG)";
	public static final String TABLE_SQL_DROP = "drop table suiluppo_equip_allocation";
	public static final String ORDER_BY_JPQL = " ORDER BY suiluppo_equip_allocation.equip_allocat_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY suiluppo_equip_allocation.equip_allocat_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.daffo.suilupposervice.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.daffo.suilupposervice.model.suiluppo_equip_allocation"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.daffo.suilupposervice.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.daffo.suilupposervice.model.suiluppo_equip_allocation"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.daffo.suilupposervice.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.daffo.suilupposervice.model.suiluppo_equip_allocation"),
			true);
	public static final long COURSE_ID_COLUMN_BITMASK = 1L;
	public static final long EQUIP_ID_COLUMN_BITMASK = 2L;
	public static final long EQUIP_ALLOCAT_ID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.daffo.suilupposervice.service.util.ServiceProps.get(
				"lock.expiration.time.com.daffo.suilupposervice.model.suiluppo_equip_allocation"));

	public suiluppo_equip_allocationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _equip_allocat_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEquip_allocat_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _equip_allocat_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return suiluppo_equip_allocation.class;
	}

	@Override
	public String getModelClassName() {
		return suiluppo_equip_allocation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("equip_allocat_id", getEquip_allocat_id());
		attributes.put("course_id", getCourse_id());
		attributes.put("equip_id", getEquip_id());
		attributes.put("equip_allocat_quantity", getEquip_allocat_quantity());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long equip_allocat_id = (Long)attributes.get("equip_allocat_id");

		if (equip_allocat_id != null) {
			setEquip_allocat_id(equip_allocat_id);
		}

		Long course_id = (Long)attributes.get("course_id");

		if (course_id != null) {
			setCourse_id(course_id);
		}

		Long equip_id = (Long)attributes.get("equip_id");

		if (equip_id != null) {
			setEquip_id(equip_id);
		}

		Long equip_allocat_quantity = (Long)attributes.get(
				"equip_allocat_quantity");

		if (equip_allocat_quantity != null) {
			setEquip_allocat_quantity(equip_allocat_quantity);
		}
	}

	@Override
	public long getEquip_allocat_id() {
		return _equip_allocat_id;
	}

	@Override
	public void setEquip_allocat_id(long equip_allocat_id) {
		_equip_allocat_id = equip_allocat_id;
	}

	@Override
	public long getCourse_id() {
		return _course_id;
	}

	@Override
	public void setCourse_id(long course_id) {
		_columnBitmask |= COURSE_ID_COLUMN_BITMASK;

		if (!_setOriginalCourse_id) {
			_setOriginalCourse_id = true;

			_originalCourse_id = _course_id;
		}

		_course_id = course_id;
	}

	public long getOriginalCourse_id() {
		return _originalCourse_id;
	}

	@Override
	public long getEquip_id() {
		return _equip_id;
	}

	@Override
	public void setEquip_id(long equip_id) {
		_columnBitmask |= EQUIP_ID_COLUMN_BITMASK;

		if (!_setOriginalEquip_id) {
			_setOriginalEquip_id = true;

			_originalEquip_id = _equip_id;
		}

		_equip_id = equip_id;
	}

	public long getOriginalEquip_id() {
		return _originalEquip_id;
	}

	@Override
	public long getEquip_allocat_quantity() {
		return _equip_allocat_quantity;
	}

	@Override
	public void setEquip_allocat_quantity(long equip_allocat_quantity) {
		_equip_allocat_quantity = equip_allocat_quantity;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			suiluppo_equip_allocation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public suiluppo_equip_allocation toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (suiluppo_equip_allocation)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		suiluppo_equip_allocationImpl suiluppo_equip_allocationImpl = new suiluppo_equip_allocationImpl();

		suiluppo_equip_allocationImpl.setEquip_allocat_id(getEquip_allocat_id());
		suiluppo_equip_allocationImpl.setCourse_id(getCourse_id());
		suiluppo_equip_allocationImpl.setEquip_id(getEquip_id());
		suiluppo_equip_allocationImpl.setEquip_allocat_quantity(getEquip_allocat_quantity());

		suiluppo_equip_allocationImpl.resetOriginalValues();

		return suiluppo_equip_allocationImpl;
	}

	@Override
	public int compareTo(suiluppo_equip_allocation suiluppo_equip_allocation) {
		long primaryKey = suiluppo_equip_allocation.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof suiluppo_equip_allocation)) {
			return false;
		}

		suiluppo_equip_allocation suiluppo_equip_allocation = (suiluppo_equip_allocation)obj;

		long primaryKey = suiluppo_equip_allocation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		suiluppo_equip_allocationModelImpl suiluppo_equip_allocationModelImpl = this;

		suiluppo_equip_allocationModelImpl._originalCourse_id = suiluppo_equip_allocationModelImpl._course_id;

		suiluppo_equip_allocationModelImpl._setOriginalCourse_id = false;

		suiluppo_equip_allocationModelImpl._originalEquip_id = suiluppo_equip_allocationModelImpl._equip_id;

		suiluppo_equip_allocationModelImpl._setOriginalEquip_id = false;

		suiluppo_equip_allocationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<suiluppo_equip_allocation> toCacheModel() {
		suiluppo_equip_allocationCacheModel suiluppo_equip_allocationCacheModel = new suiluppo_equip_allocationCacheModel();

		suiluppo_equip_allocationCacheModel.equip_allocat_id = getEquip_allocat_id();

		suiluppo_equip_allocationCacheModel.course_id = getCourse_id();

		suiluppo_equip_allocationCacheModel.equip_id = getEquip_id();

		suiluppo_equip_allocationCacheModel.equip_allocat_quantity = getEquip_allocat_quantity();

		return suiluppo_equip_allocationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{equip_allocat_id=");
		sb.append(getEquip_allocat_id());
		sb.append(", course_id=");
		sb.append(getCourse_id());
		sb.append(", equip_id=");
		sb.append(getEquip_id());
		sb.append(", equip_allocat_quantity=");
		sb.append(getEquip_allocat_quantity());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.daffo.suilupposervice.model.suiluppo_equip_allocation");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>equip_allocat_id</column-name><column-value><![CDATA[");
		sb.append(getEquip_allocat_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>course_id</column-name><column-value><![CDATA[");
		sb.append(getCourse_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>equip_id</column-name><column-value><![CDATA[");
		sb.append(getEquip_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>equip_allocat_quantity</column-name><column-value><![CDATA[");
		sb.append(getEquip_allocat_quantity());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = suiluppo_equip_allocation.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			suiluppo_equip_allocation.class
		};
	private long _equip_allocat_id;
	private long _course_id;
	private long _originalCourse_id;
	private boolean _setOriginalCourse_id;
	private long _equip_id;
	private long _originalEquip_id;
	private boolean _setOriginalEquip_id;
	private long _equip_allocat_quantity;
	private long _columnBitmask;
	private suiluppo_equip_allocation _escapedModel;
}