/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.daffo.wiki_node_tableservice.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the wiki_node_table service. Represents a row in the &quot;wiki_node_table&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.daffo.wiki_node_tableservice.model.impl.wiki_node_tableModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.daffo.wiki_node_tableservice.model.impl.wiki_node_tableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see wiki_node_table
 * @see com.daffo.wiki_node_tableservice.model.impl.wiki_node_tableImpl
 * @see com.daffo.wiki_node_tableservice.model.impl.wiki_node_tableModelImpl
 * @generated
 */
@ProviderType
public interface wiki_node_tableModel extends BaseModel<wiki_node_table> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wiki_node_table model instance should use the {@link wiki_node_table} interface instead.
	 */

	/**
	 * Returns the primary key of this wiki_node_table.
	 *
	 * @return the primary key of this wiki_node_table
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wiki_node_table.
	 *
	 * @param primaryKey the primary key of this wiki_node_table
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the node ID of this wiki_node_table.
	 *
	 * @return the node ID of this wiki_node_table
	 */
	public long getNodeID();

	/**
	 * Sets the node ID of this wiki_node_table.
	 *
	 * @param NodeID the node ID of this wiki_node_table
	 */
	public void setNodeID(long NodeID);

	/**
	 * Returns the node name of this wiki_node_table.
	 *
	 * @return the node name of this wiki_node_table
	 */
	@AutoEscape
	public String getNodeName();

	/**
	 * Sets the node name of this wiki_node_table.
	 *
	 * @param NodeName the node name of this wiki_node_table
	 */
	public void setNodeName(String NodeName);

	/**
	 * Returns the node description of this wiki_node_table.
	 *
	 * @return the node description of this wiki_node_table
	 */
	@AutoEscape
	public String getNodeDescription();

	/**
	 * Sets the node description of this wiki_node_table.
	 *
	 * @param NodeDescription the node description of this wiki_node_table
	 */
	public void setNodeDescription(String NodeDescription);

	/**
	 * Returns the node creation date of this wiki_node_table.
	 *
	 * @return the node creation date of this wiki_node_table
	 */
	@AutoEscape
	public String getNodeCreationDate();

	/**
	 * Sets the node creation date of this wiki_node_table.
	 *
	 * @param NodeCreationDate the node creation date of this wiki_node_table
	 */
	public void setNodeCreationDate(String NodeCreationDate);

	/**
	 * Returns the node creator of this wiki_node_table.
	 *
	 * @return the node creator of this wiki_node_table
	 */
	@AutoEscape
	public String getNodeCreator();

	/**
	 * Sets the node creator of this wiki_node_table.
	 *
	 * @param NodeCreator the node creator of this wiki_node_table
	 */
	public void setNodeCreator(String NodeCreator);

	/**
	 * Returns the node modification date of this wiki_node_table.
	 *
	 * @return the node modification date of this wiki_node_table
	 */
	@AutoEscape
	public String getNodeModificationDate();

	/**
	 * Sets the node modification date of this wiki_node_table.
	 *
	 * @param NodeModificationDate the node modification date of this wiki_node_table
	 */
	public void setNodeModificationDate(String NodeModificationDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.daffo.wiki_node_tableservice.model.wiki_node_table wiki_node_table);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.daffo.wiki_node_tableservice.model.wiki_node_table> toCacheModel();

	@Override
	public com.daffo.wiki_node_tableservice.model.wiki_node_table toEscapedModel();

	@Override
	public com.daffo.wiki_node_tableservice.model.wiki_node_table toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}