/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.daffo.wiki_node_tableservice.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the wiki_page_table service. Represents a row in the &quot;wiki_page_table&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.daffo.wiki_node_tableservice.model.impl.wiki_page_tableModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.daffo.wiki_node_tableservice.model.impl.wiki_page_tableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see wiki_page_table
 * @see com.daffo.wiki_node_tableservice.model.impl.wiki_page_tableImpl
 * @see com.daffo.wiki_node_tableservice.model.impl.wiki_page_tableModelImpl
 * @generated
 */
@ProviderType
public interface wiki_page_tableModel extends BaseModel<wiki_page_table> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a wiki_page_table model instance should use the {@link wiki_page_table} interface instead.
	 */

	/**
	 * Returns the primary key of this wiki_page_table.
	 *
	 * @return the primary key of this wiki_page_table
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this wiki_page_table.
	 *
	 * @param primaryKey the primary key of this wiki_page_table
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the page ID of this wiki_page_table.
	 *
	 * @return the page ID of this wiki_page_table
	 */
	public long getPageID();

	/**
	 * Sets the page ID of this wiki_page_table.
	 *
	 * @param PageID the page ID of this wiki_page_table
	 */
	public void setPageID(long PageID);

	/**
	 * Returns the page name of this wiki_page_table.
	 *
	 * @return the page name of this wiki_page_table
	 */
	@AutoEscape
	public String getPageName();

	/**
	 * Sets the page name of this wiki_page_table.
	 *
	 * @param PageName the page name of this wiki_page_table
	 */
	public void setPageName(String PageName);

	/**
	 * Returns the page description of this wiki_page_table.
	 *
	 * @return the page description of this wiki_page_table
	 */
	@AutoEscape
	public String getPageDescription();

	/**
	 * Sets the page description of this wiki_page_table.
	 *
	 * @param PageDescription the page description of this wiki_page_table
	 */
	public void setPageDescription(String PageDescription);

	/**
	 * Returns the page rating of this wiki_page_table.
	 *
	 * @return the page rating of this wiki_page_table
	 */
	@AutoEscape
	public String getPageRating();

	/**
	 * Sets the page rating of this wiki_page_table.
	 *
	 * @param PageRating the page rating of this wiki_page_table
	 */
	public void setPageRating(String PageRating);

	/**
	 * Returns the page version of this wiki_page_table.
	 *
	 * @return the page version of this wiki_page_table
	 */
	@AutoEscape
	public String getPageVersion();

	/**
	 * Sets the page version of this wiki_page_table.
	 *
	 * @param PageVersion the page version of this wiki_page_table
	 */
	public void setPageVersion(String PageVersion);

	/**
	 * Returns the node ID of this wiki_page_table.
	 *
	 * @return the node ID of this wiki_page_table
	 */
	public long getNodeID();

	/**
	 * Sets the node ID of this wiki_page_table.
	 *
	 * @param NodeID the node ID of this wiki_page_table
	 */
	public void setNodeID(long NodeID);

	/**
	 * Returns the page_ creation_ date of this wiki_page_table.
	 *
	 * @return the page_ creation_ date of this wiki_page_table
	 */
	@AutoEscape
	public String getPage_Creation_Date();

	/**
	 * Sets the page_ creation_ date of this wiki_page_table.
	 *
	 * @param Page_Creation_Date the page_ creation_ date of this wiki_page_table
	 */
	public void setPage_Creation_Date(String Page_Creation_Date);

	/**
	 * Returns the page_creator of this wiki_page_table.
	 *
	 * @return the page_creator of this wiki_page_table
	 */
	@AutoEscape
	public String getPage_creator();

	/**
	 * Sets the page_creator of this wiki_page_table.
	 *
	 * @param Page_creator the page_creator of this wiki_page_table
	 */
	public void setPage_creator(String Page_creator);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.daffo.wiki_node_tableservice.model.wiki_page_table wiki_page_table);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.daffo.wiki_node_tableservice.model.wiki_page_table> toCacheModel();

	@Override
	public com.daffo.wiki_node_tableservice.model.wiki_page_table toEscapedModel();

	@Override
	public com.daffo.wiki_node_tableservice.model.wiki_page_table toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}