/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.daffo.prontuario_drugservice.service.base;

import aQute.bnd.annotation.ProviderType;

import com.daffo.prontuario_drugservice.model.prontuario_drug;
import com.daffo.prontuario_drugservice.service.persistence.prontuario_drugPersistence;
import com.daffo.prontuario_drugservice.service.prontuario_drugLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the prontuario_drug local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.daffo.prontuario_drugservice.service.impl.prontuario_drugLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.daffo.prontuario_drugservice.service.impl.prontuario_drugLocalServiceImpl
 * @see com.daffo.prontuario_drugservice.service.prontuario_drugLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class prontuario_drugLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements prontuario_drugLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.daffo.prontuario_drugservice.service.prontuario_drugLocalServiceUtil} to access the prontuario_drug local service.
	 */

	/**
	 * Adds the prontuario_drug to the database. Also notifies the appropriate model listeners.
	 *
	 * @param prontuario_drug the prontuario_drug
	 * @return the prontuario_drug that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public prontuario_drug addprontuario_drug(prontuario_drug prontuario_drug) {
		prontuario_drug.setNew(true);

		return prontuario_drugPersistence.update(prontuario_drug);
	}

	/**
	 * Creates a new prontuario_drug with the primary key. Does not add the prontuario_drug to the database.
	 *
	 * @param drug_id the primary key for the new prontuario_drug
	 * @return the new prontuario_drug
	 */
	@Override
	public prontuario_drug createprontuario_drug(long drug_id) {
		return prontuario_drugPersistence.create(drug_id);
	}

	/**
	 * Deletes the prontuario_drug with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param drug_id the primary key of the prontuario_drug
	 * @return the prontuario_drug that was removed
	 * @throws PortalException if a prontuario_drug with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public prontuario_drug deleteprontuario_drug(long drug_id)
		throws PortalException {
		return prontuario_drugPersistence.remove(drug_id);
	}

	/**
	 * Deletes the prontuario_drug from the database. Also notifies the appropriate model listeners.
	 *
	 * @param prontuario_drug the prontuario_drug
	 * @return the prontuario_drug that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public prontuario_drug deleteprontuario_drug(
		prontuario_drug prontuario_drug) {
		return prontuario_drugPersistence.remove(prontuario_drug);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(prontuario_drug.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return prontuario_drugPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.daffo.prontuario_drugservice.model.impl.prontuario_drugModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return prontuario_drugPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.daffo.prontuario_drugservice.model.impl.prontuario_drugModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return prontuario_drugPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return prontuario_drugPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return prontuario_drugPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public prontuario_drug fetchprontuario_drug(long drug_id) {
		return prontuario_drugPersistence.fetchByPrimaryKey(drug_id);
	}

	/**
	 * Returns the prontuario_drug with the primary key.
	 *
	 * @param drug_id the primary key of the prontuario_drug
	 * @return the prontuario_drug
	 * @throws PortalException if a prontuario_drug with the primary key could not be found
	 */
	@Override
	public prontuario_drug getprontuario_drug(long drug_id)
		throws PortalException {
		return prontuario_drugPersistence.findByPrimaryKey(drug_id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(prontuario_drugLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(prontuario_drug.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("drug_id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(prontuario_drugLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(prontuario_drug.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("drug_id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(prontuario_drugLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(prontuario_drug.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("drug_id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return prontuario_drugLocalService.deleteprontuario_drug((prontuario_drug)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return prontuario_drugPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the prontuario_drugs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.daffo.prontuario_drugservice.model.impl.prontuario_drugModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of prontuario_drugs
	 * @param end the upper bound of the range of prontuario_drugs (not inclusive)
	 * @return the range of prontuario_drugs
	 */
	@Override
	public List<prontuario_drug> getprontuario_drugs(int start, int end) {
		return prontuario_drugPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of prontuario_drugs.
	 *
	 * @return the number of prontuario_drugs
	 */
	@Override
	public int getprontuario_drugsCount() {
		return prontuario_drugPersistence.countAll();
	}

	/**
	 * Updates the prontuario_drug in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param prontuario_drug the prontuario_drug
	 * @return the prontuario_drug that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public prontuario_drug updateprontuario_drug(
		prontuario_drug prontuario_drug) {
		return prontuario_drugPersistence.update(prontuario_drug);
	}

	/**
	 * Returns the prontuario_drug local service.
	 *
	 * @return the prontuario_drug local service
	 */
	public prontuario_drugLocalService getprontuario_drugLocalService() {
		return prontuario_drugLocalService;
	}

	/**
	 * Sets the prontuario_drug local service.
	 *
	 * @param prontuario_drugLocalService the prontuario_drug local service
	 */
	public void setprontuario_drugLocalService(
		prontuario_drugLocalService prontuario_drugLocalService) {
		this.prontuario_drugLocalService = prontuario_drugLocalService;
	}

	/**
	 * Returns the prontuario_drug persistence.
	 *
	 * @return the prontuario_drug persistence
	 */
	public prontuario_drugPersistence getprontuario_drugPersistence() {
		return prontuario_drugPersistence;
	}

	/**
	 * Sets the prontuario_drug persistence.
	 *
	 * @param prontuario_drugPersistence the prontuario_drug persistence
	 */
	public void setprontuario_drugPersistence(
		prontuario_drugPersistence prontuario_drugPersistence) {
		this.prontuario_drugPersistence = prontuario_drugPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.daffo.prontuario_drugservice.model.prontuario_drug",
			prontuario_drugLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.daffo.prontuario_drugservice.model.prontuario_drug");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return prontuario_drugLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return prontuario_drug.class;
	}

	protected String getModelClassName() {
		return prontuario_drug.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = prontuario_drugPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = prontuario_drugLocalService.class)
	protected prontuario_drugLocalService prontuario_drugLocalService;
	@BeanReference(type = prontuario_drugPersistence.class)
	protected prontuario_drugPersistence prontuario_drugPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}