/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package istruzioni_per_la_compilazioneservice.model.impl;

import aQute.bnd.annotation.ProviderType;

import istruzioni_per_la_compilazioneservice.model.istruzioni_per_la_compilazione;

import istruzioni_per_la_compilazioneservice.service.istruzioni_per_la_compilazioneLocalServiceUtil;

/**
 * The extended model base implementation for the istruzioni_per_la_compilazione service. Represents a row in the &quot;istruzioni_per_la_compilazione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link istruzioni_per_la_compilazioneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see istruzioni_per_la_compilazioneImpl
 * @see istruzioni_per_la_compilazione
 * @generated
 */
@ProviderType
public abstract class istruzioni_per_la_compilazioneBaseImpl
	extends istruzioni_per_la_compilazioneModelImpl
	implements istruzioni_per_la_compilazione {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a istruzioni_per_la_compilazione model instance should use the {@link istruzioni_per_la_compilazione} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			istruzioni_per_la_compilazioneLocalServiceUtil.addistruzioni_per_la_compilazione(this);
		}
		else {
			istruzioni_per_la_compilazioneLocalServiceUtil.updateistruzioni_per_la_compilazione(this);
		}
	}
}